326 bake config sparse
GPLgithub/tk-core pull request #1
Opened 2018-06-19 21:37 UTC by kporangehat

Adds a --sparse option that will skip caching app_store bundles to keep baked configs smaller. 

Fixes a bug in tk-core that would skip checking if an engine's apps needed to be cached if the parent engine was skipped.

2018-06-20 08:25 UTC, gplsteph requested changes
Requesting changes for the following reasons:
- I think we still want to cache tk-core if sparse caching is off. If it is on, we shouldn't cache it only if dealing with an app store release.
- Please revisit the `_should_skip_caching` override. I feel the right approach would be to give the callable as a param.
- Our goal is to submit these changes back onto SG tk-core, so headers should be preserved and we shouldn't have any "studio" naming.
Thanks!

2018-06-20 08:25 UTC, gplsteph commented on developer/bake_config.py
> +# Copyright 2018 GPL Solutions, LLC.  All rights reserved.
In this case we want to preserve the original headers and push back these changes onto the SG repo. I have a PR for it on Shotgun Software. So please put back the Shotgun Software header.

2018-06-20 08:25 UTC, gplsteph commented on developer/bake_config.py
> +    :param make_sparse: Don't cache app_store bundles into the config. Defaults to False.
What about naming this param `sparse_caching`? `make_sparse` is a bit vague to me?

2018-06-20 08:25 UTC, gplsteph commented on developer/bake_config.py
> +def _studio_should_skip_caching(desc):
Having _studio_ in this method name does not seem right, as we intent to submit these changes for a PR on SG repo. What about `should_skip_caching_sparse`?

2018-06-20 08:25 UTC, gplsteph commented on developer/bake_config.py
> -    if config_descriptor.associated_core_descriptor:
Just checking: from now on we never cache tk-core, even if there is an associated core descriptor? Should we cache it if the sparse option is off? What if we have a special tk-core release we want to pull from our github and not from the app store?

2018-06-20 08:25 UTC, gplsteph commented on developer/bake_config.py
> +        caching._should_skip_caching = _studio_should_skip_caching
That does not seem right. Why not adding an extra param to `cache_apps` which would be a callable to call when deciding what to skip or not? The default value could either be `_should_skip_caching`, or `None` if preferred. For the latter case, the `cache_apps` code would fallback to calling `_should_skip_caching` if the param is `None`, and blindly call the callable otherwise? This would give some flexibility to decide what needs to be cached or not and would solve a general case, as opposed to just our own very specific case?

2018-06-20 08:25 UTC, gplsteph commented on developer/utils/caching.py
> +            if not _should_skip_caching(desc):
See my previous comments, but I feel the callable should be a param of `cache_apps`, and fall back by default on `_should_skip_caching`.

2018-06-20 16:23 UTC, kporangehat commented on developer/bake_config.py
> +        caching._should_skip_caching = _studio_should_skip_caching
Do we need this to be a callable or could we just pass in the descriptor types we want to skip as a `list` of `str`s (for example `should_skip=["dev", "path", "app_store"]`). I agree callable would be more flexible but as it stands we'd only have the descriptor type as a `str` to work with so there's not a ton we could do with that.

2018-06-20 20:16 UTC, kporangehat commented
Ready for review again.

2018-06-21 08:58 UTC, gplsteph approved these changes
Looks good to me, a couple of small things could be possibly improved, or not.
Thanks.

2018-06-21 08:58 UTC, gplsteph commented on developer/bake_config.py
> +    caching, cache_apps, authenticate, add_authentication_options,
Do we need to import `caching` now that we don't monkey patch it anymore?

2018-06-21 08:58 UTC, gplsteph commented on developer/bake_config.py
> +    # If sparse_caching is True, we add app_store descriptor types to the skip
```
# If spare_caching is True we use our own descriptor filter which skips app_store descriptor 
#to keep our bundle cache small and let Toolkit download the bundles from the Apps store
```
?
Saying _we add app_store descriptors_ is a bit confusing here...

2018-06-21 08:58 UTC, gplsteph commented on developer/bake_config.py
> +    if sparse_caching:
I think something like:
```
if sparse_caching:
   logger.info("Performing sparse caching. Will not cache standard app_store bundles")
    cache_apps(sg_connection, config_descriptor, bundle_cache_root, _should_skip_caching_sparse)
else:
    cache_apps(sg_connection, config_descriptor, bundle_cache_root)
```
would be a lot clearer.

2018-06-21 08:58 UTC, gplsteph commented on developer/bake_config.py
> +        if not sparse_caching or not _should_skip_caching_sparse(core_descriptor):
A comment would be helpful here, something like `If sparse_caching is on, check if we need to cache tk-core or not`.

2018-06-22 17:59 UTC, merged